#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   🚀 HyperServe Customer Mobile App - START INSTRUCTIONS     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  IMPORTANT: This is NOT the web admin panel!"
echo "   The mobile app runs separately using Expo."
echo ""
echo "📱 Where you are NOW:"
echo "   Browser: Web Admin Panel (Super Admin, Tenant Admin)"
echo "   URL: https://hyperserve-food-mvp.preview.emergentagent.com"
echo ""
echo "📱 Where you need to GO:"
echo "   Terminal/Command Line → Run the commands below"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    HOW TO START                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  Open a NEW terminal/shell window"
echo ""
echo "2️⃣  Run these commands:"
echo "    cd /app/mobile-app"
echo "    yarn start"
echo ""
echo "3️⃣  Wait 10-20 seconds for Metro bundler to start"
echo ""
echo "4️⃣  You'll see a QR CODE in the TERMINAL (not browser!)"
echo ""
echo "5️⃣  Scan QR code with:"
echo "    📱 iOS: Camera app"
echo "    📱 Android: Expo Go app"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                 WHAT YOU'LL SEE                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "In the TERMINAL, you'll see:"
echo ""
echo "  ┌─────────────────────────────────────┐"
echo "  │                                     │"
echo "  │    ███ ▄▄▄▄▄ █▀█ █▄█▀ ▀▄▄▄ ▀█     │"
echo "  │    ███ █   █ █▀▀▀█ ▀█▄▀▄ █▄▀█     │"
echo "  │    ███ █▄▄▄█ █▀ █▀▀▀█▀ █▀▀ ▄█     │"
echo "  │    (QR CODE - scan with phone)      │"
echo "  │                                     │"
echo "  └─────────────────────────────────────┘"
echo ""
echo "  › Metro waiting on exp://192.168.x.x:8081"
echo "  › Press a │ open Android"
echo "  › Press i │ open iOS simulator"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                 QUICK START NOW                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Ready to start? Press ENTER to launch the mobile app..."
read

cd /app/mobile-app
yarn start
